Repository nix-prefab/nix-basement, pull requests merged in 2022-10, with the labels that each got.

#28 docs: add readme
  README.adoc
  README.md
Labels: hacktoberfest

#29 docs: we need more badges
  README.adoc
Labels: hacktoberfest

#24 fix: mkEnableableModule
  lib/modules.nix
Labels: bug

#23 feat: pass metaConfig as a special arg
  lib/configurations.nix
Labels: enhancement

#38 fix: nixpkgs.overlays
  flake.nix
  lib/configurations.nix
  lib/packages.nix
Labels: bug, hacktoberfest-accepted

#35 feat: k3s module
  nixos-modules/services/k3s.nix
Labels: enhancement, hacktoberfest-accepted

#34 docs: change docs link to new domain
  README.adoc
Labels: hacktoberfest-accepted
